version: '3.8'

services:
  api:
    container_name: api
    build:
      context: backend/api
      dockerfile: Dockerfile
      target: development
    command: yarn start:dev
    environment:
      # skips certificate validation when request incomming inside container
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    ports:
      - '4000:4000'
    volumes:
      - ./backend/api/:/usr/src/app/
      - /usr/src/app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - docker-ssl
  web:
    container_name: web
    build:
      context: frontend/web
      dockerfile: Dockerfile
      target: development
    command: yarn dev
    ports:
      - '3000:3000'
    environment:
      # skips certificate validation when request incomming inside container
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    depends_on:
      - api
    networks:
      - docker-ssl
    volumes:
      - ./frontend/web/:/usr/src/web
      - /usr/src/web/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped
    networks:
      - docker-ssl
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - web
      - api
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/certs/cert.pem:/ssl/cert.pem
      - ./.docker/nginx/certs/key.pem:/ssl/key.pem
      - ./.docker/nginx/log:/log

networks:
  docker-ssl:
    driver: bridge
