version: '3.8'

services:
  api:
    container_name: api
    build:
      context: ./backend/api
      dockerfile: Dockerfile
      target: development
    ports:
      - '4000:4000'
    volumes:
      - ./backend/api/:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - api
  web:
    container_name: web
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
      target: development
    ports:
      - '3000:3000'
    depends_on:
      - api
    networks:
      - web
    volumes:
      - ./frontend/web/:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped
    networks:
      - api
      - web
    depends_on:
      - web
      - api
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/certs:/ssl
      - ./.docker/nginx/log:/log

networks:
  api:
    driver: bridge
  web:
    driver: bridge
